### PR TITLE
README: add missing line in manual steps

### PR DESCRIPTION
**Pull request by philips**
cd required for git clone to land into right dir

### CODE REVIEW

**Comment by ojarjur** [comment]
Thanks for catching and fixing this!

**Comment by philips** [comment]
No problem. I caught it because the new go 1.11 modules stuff breaks the old `go get github.com/google/git-appraise-web` workflow... :(

**Comment by ojarjur** [comment]
@philips Well that's certainly not good.

Can you share the error you are seeing? I've just tried `go get github.com/google/git-appraise-web/git-appraise-web` after installing go 1.11, but wasn't able to reproduce an issue.

**Comment by philips** [comment]
```
$ env | grep GO111
GO111MODULE=on

$ go get github.com/google/git-appraise-web/git-appraise-web
go: cannot find main module; see 'go help modules'
```

**Comment by philips** [comment]
To be clear this isn't an issue with git-appraise-web it is just how the new go mod stuff works.

**Pull request merged**
